#include "../lib/esphttpd/httpd/httpd.h"
#include "../lib/esphttpd/user/io.h"
#include "../lib/esphttpd/httpd/httpdespfs.h"
#include "../lib/esphttpd/user/cgi.h"
#include "../lib/esphttpd/user/cgiwifi.h"
#include "../lib/esphttpd/user/stdout.h"
